# 第1章 評価行列

In [ ]:
import numpy as np

In [ ]:
Du = np.array([
          [5, 3, +1],
          [6, 2, +1],
          [4, 1, +1],
          [8, 5, -1],
          [2, 4, -1],
          [3, 6, -1],
          [7, 6, -1],
          [4, 2, np.nan],
          [5, 1, np.nan],
          [8, 6, np.nan],
          [3, 4, np.nan],
          [4, 7, np.nan],
          [4, 4, np.nan],
])

In [ ]:
print(f"Du = \n{Du}")

Du = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]
 [ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


In [ ]:
print(f"Duの形状 = {Du.shape}")
print(f"Duの行数 = {Du.shape[0]}")
print(f"Duの列数 = {Du.shape[1]}")
print(f"Duの全要素数 = {Du.size}")

Duの形状 = (13, 3)
Duの行数 = 13
Duの列数 = 3
Duの全要素数 = 39


In [ ]:
# アイテム集合
I = np.arange(Du.shape[0])
print(f"I = {I}")

# アイテムの特徴ベクトル
print(f"x = \n{Du[:, :2]}")

# アイテムiの特徴ベクトル
i = 0
print(f"x{i} = {Du[i, :2]}")

I = [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
x = 
[[5. 3.]
 [6. 2.]
 [4. 1.]
 [8. 5.]
 [2. 4.]
 [3. 6.]
 [7. 6.]
 [4. 2.]
 [5. 1.]
 [8. 6.]
 [3. 4.]
 [4. 7.]
 [4. 4.]]
x0 = [5. 3.]


In [ ]:
# 評価地集合
ru = Du[:, 2]
print(f"ru = {ru}")

print(f"ruの形状 = {ru.shape}")
print(f"ruの全要素数 = {ru.size}")

i, j = 2, 5
print(f"ru{i}からru{j}までの評価値 = {ru[i:j+1]}")
print(f"ruの逆順 = {ru[::-1]}")

i = 0
print(f"ru{i} = {ru[i]}")


ru = [ 1.  1.  1. -1. -1. -1. -1. nan nan nan nan nan nan]
ruの形状 = (13,)
ruの全要素数 = 13
ru2からru5までの評価値 = [ 1. -1. -1. -1.]
ruの逆順 = [nan nan nan nan nan nan -1. -1. -1. -1.  1.  1.  1.]
ru0 = 1.0


In [ ]:
# アイテム集合
print(f"ユーザーuが未評価 = {np.isnan(ru)}")
print(f"ユーザーuが評価済み = {~np.isnan(ru)}")

Iu = I[~np.isnan(ru)]
print(f"Iu = {Iu}")

Iup = I[ru == 1]
print(f"Iu+ = {Iup}")

Iun = I[ru == -1]
print(f"Iu- = {Iun}")

Iu_not = I[np.isnan(ru)]
print(f"Iu_not = {Iu_not}")

ユーザーuが未評価 = [False False False False False False False  True  True  True  True  True
  True]
ユーザーuが評価済み = [ True  True  True  True  True  True  True False False False False False
 False]
Iu = [0 1 2 3 4 5 6]
Iu+ = [0 1 2]
Iu- = [3 4 5 6]
Iu_not = [ 7  8  9 10 11 12]


In [ ]:
# 訓練データと予測対象データ
DuL = Du[Iu]
print(f"DuL = \n{DuL}")
print(f"|DuL| = {DuL.shape}")
print(f"|DuL+| = {DuL[DuL[:, 2] > 0].shape[1]}")

DuU = Du[Iu_not]
print(f"DuU = \n{DuU}")

print(f"|DuU| = {DuU.shape[0]}")

DuL = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]]
|DuL| = (7, 3)
|DuL+| = 3
DuU = 
[[ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]
|DuU| = 6
